### ISSUE TITLE
Feature: see translation

### ISSUE THREAD

**Issue by mikestaub** [bluesky-social/react-native-uitextview#14]
Currently, users have to click out of the native apps to view the translated post content in Google Translate. Ideally, there would simply be a 'see translation' button near the text like in Instagram.

This can be done in a straightforward way using existing libraries. An offline implementation would make the translations faster as well as save on API costs.

https://github.com/yaaliuzhipeng/fast-mlkit-translate-text

**Comment by fobos531** [comment]
Hello @mikestaub, I think this issue is not really relevant to this package, it is more aimed at the Bluesky app itself.
