### ISSUE TITLE
How did you make RN accept putting JSX text inside this component without exploding?

### ISSUE THREAD

**Issue by MicroDroid** [bluesky-social/react-native-uitextview#15]
Not really an issue but discussions are off for this repo and I hope you don't mind me asking here 🙃

I'm trying to implement a similar thing for Android and when I use my own component like:

```tsx
<CustomText>
    hi
</CustomText>
```

React Native goes ([error origin](https://github.com/facebook/react-native/blob/a026d6d2509255e42b9543fdeab0d1472bcda360/packages/react-native/Libraries/Renderer/implementations/ReactFabric-dev.js#L1973)):

```
Text strings must be rendered within a <Text> component.
```

And the only way around this is to wrap `hi` with a `<RNText>` (which is bad, because it breaks virtualization etc).

How did you make your component work without this constraint?

**Comment by haileyok** [comment]
No problem at all!

It definitely might be possible to do this some other way, but I simply resorted to passing it as a prop on the native component like here https://github.com/bluesky-social/react-native-uitextview/blob/main/src/Text.tsx#L82

**Comment by MicroDroid** [comment]
Ohhh I got it! Yesterday I was fiddling with RN's source and it got soooo crazy.

I'll just use this method too, thanks again :)
