### ISSUE TITLE
Background color style does not work with nested text

### ISSUE THREAD

**Issue by jobpaardekooper** [bluesky-social/react-native-uitextview#2]
The following code displays the text with a white background:
```tsx
<UITextView selectable uiTextView >
    <UITextView selectable uiTextView style={{ backgroundColor: "#ff0000" }} >test 1</UITextView>
    <UITextView selectable uiTextView style={{ backgroundColor: "#00ff00" }} >test 2</UITextView>
</UITextView>
```

Using a single, non-nested component with a `backgroundColor` works:
```tsx
<UITextView selectable uiTextView style={{ backgroundColor: "#ff0000" }} >test 1</UITextView>
```

Also giving the container a background color works. But I want to give only a part of the text a background. Other styles like `color` are working as expected. Just seems to be an issue with `backgroundColor`.

**Comment by haileyok** [comment]
This is a super late response...anyway, I added `backgroundColor` support. It's available in old architecture with `1.4.0`, or new architecture in `2.0.0-rc.0`
