### ISSUE TITLE
Empty text content crashes the app on iOS

### ISSUE THREAD

**Issue by jobpaardekooper** [bluesky-social/react-native-uitextview#3]
If you have the following component on iOS it will crash:
```tsx
<UITextView selectable uiTextView ></UITextView>
```

The following does work without any problems:
```tsx
<UITextView selectable uiTextView >{ "" }</UITextView>
```

It might happen that there is some logic in your app where `undefined` ends up being inside the component and that will cause a crash. This does not happen on the normal react native `Text` component.

Here is the crash form inside xcode:
```
Thread 4: Swift runtime failure: Double value cannot be converted to Int because it is either infinite or NaN
```
<img width="1197" alt="Screenshot 2024-03-31 at 15 22 04" src="https://github.com/bluesky-social/react-native-uitextview/assets/34612663/2f78134a-71bc-4e20-9128-74086520e00f">

Seems like a division by zero issue to me.

**Comment by haileyok** [comment]
Fixed the error in the native code, but still need to adjust for the "default" view height. Thanks for the report!
