### ISSUE TITLE
IOS uiTextView on Expo go

### ISSUE THREAD

**Issue by again-this-coder** [bluesky-social/react-native-uitextview#9]
Hi, 
I'm really enjoying this library and I am using it for my Expo go project. it works great on android and selectable works on IOS. 
the issue I am facing is that I can't use uiTextView on my Expo go project. Is it possible for you to make an update on this and add this functionality for the Expo go projects

**Comment by haileyok** [comment]
Hi @again-this-coder! Unfortunately, this isn't possible as this library introduced custom native code for iOS. You would need to create an Expo development client to use the `uiTextView` prop.

See https://docs.expo.dev/workflow/using-libraries/#determining-third-party-library-compatibility and https://docs.expo.dev/develop/development-builds/introduction/

Best of luck!
